networks:
  wagon_bid:
    external: true

services:
  plants_back:
    container_name: plants_back
    image: inferno681/plants_back:latest
    restart: always
    volumes:
      - ./config.yaml:/app/src/config/config.yaml
    env_file:
      - .env
    ports:
      - 9080:8000
    networks:
      - wagon_bid
