service:
  title: Plants bot info
  description: Show plants info
  host: "0.0.0.0"
  port: 8000
  timeout: 60
  workers: 4

  link_ttl: 300

  service_chat_id: 459335857

  debug: false

  is_prod: false

  tag_metadata_auth_web:
    name: "Auth web"
    description: "Registration and authentication for web"
  tag_metadata_auth_telegram:
    name: "Auth telegram"
    description: "Registration and authentication for telegram"
  tag_metadata_auth_bot:
    name: "Auth bot"
    description: "Authentication for bot"
  tag_metadata_plant:
    name: "Plant"
    description: "Plants operations"
  tag_metadata_bot:
    name: "Bot API"
    description: "Bot operations"
  tag_metadata_user:
    name: "User"
    description: "User operations"
  tag_metadata_link:
    name: "Telegram link"
    description: "Telegram links operations"
  tag_metadata_health:
    name: "Health"
    description: "Health endpoints. For services only!"

auth:
  access_token_ttl: 1800
  refresh_token_ttl: 14400
  max_sessions_per_user: 10

  user_init_data_ttl: 86400
  init_data_skew: 60
  bot_init_data_ttl: 300

redis:
  host: localhost
  port: 6379
  decode_responses: true
  sid_db: 0

  queue_db: 1

  taskiq_db: 2
  results_db: 3

  conf_db: 4

mongodb:
  host: "127.0.0.1"
  port: 27017
  db: "plants_bot"
  max_retries: 3
  backoff_base: 0.05
  backoff_jitter: 0.05

cors:
  allow_origins:
    - "http://127.0.0.1:5173"
    - "http://localhost:5173"
    - "https://localhost:5173"
    - "https://127.0.0.1:8000"
  allow_credentials: true
  allow_methods:
    - "*"
  allow_headers:
    - "*"
image:
  allowed_mime:
    - "image/jpeg"
    - "image/png"
    - "image/webp"
  allowed_ext:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".webp"
  max_size_bytes: 5242880

  out_width: 512
  out_height: 512
  jpeg_quality: 85
  webp_quality: 80

  max_input_width: 4096
  max_input_height: 4096
  max_input_pixels: 20000000

  backend: "pillow"

  max_workers: 8

logger:
  format: "[%(asctime)s.%(msecs)03d] PID:%(process)-5d %(funcName)-35s %(module)-12s:%(lineno)-4d %(levelname)-7s - %(message)s"
  exclude:
    - "/api/v1/healthz"
  date_format: "%Y-%m-%d %H:%M:%S"
  level: "INFO"

storage:
  bucket: plants
  endpoint_url: https://storage-wagonbid.ddns.net
